title: Li Dingxin
email: li_ding_xin@foxmail.com
description: >- # this means to ignore newlines until "baseurl:"
  网站简介
# 网站的基础url
url: "http://www.lidingxin.top/" 
# 插件
plugins:
  - jekyll-feed
  - jekyll-sass-converter
# 导航栏
nav:
  - title: 主页
    url: /
  - title: 博客
    url: /blogs
# 其他页面
include:
  - _pages
# 阿里云oss
oss_base_url:
  - "https://lidingxin-top.oss-cn-beijing.aliyuncs.com"